
export const AUDIT_ACTION = {
    INVITATION_SENT: "INVITATION_SENT",
    INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
    ROLE_CHANGED: "ROLE_CHANGED",
    MEMBER_REMOVED: "MEMBER_REMOVED",
    ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED",
    PERMISSION_UPDATED: "PERMISSION_UPDATED",
    ORGANIZATION_CREATED: "ORGANIZATION_CREATED"
};