
const NOTIFICATION_TYPE = {
    INVITATION_SENT: "INVITATION_SENT",
    INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
    ROLE_CHANGED: "ROLE_CHANGED",
    MEMBER_JOINED: "MEMBER_JOINED",
    MEMBER_REMOVED: "MEMBER_REMOVED",
    ORGANIZATION_UPDATED: "ORGANIZATION_UPDATED"
};

export { NOTIFICATION_TYPE };