
const ROLES = {
    OWNER: 'OWNER',
    ADMIN: 'ADMIN',
    MEMBER: 'MEMBER'
};

const PERMISSIONS = {
    INVITE_MEMBERS: 'invite:members',
    REMOVE_MEMBERS: 'remove:members',
    CHANGE_ROLES: 'change:roles',
    VIEW_ORGANIZATION: 'view:organization'
};

const ROLE_PERMISSION  = {
    [ ROLES.OWNER ] : [ PERMISSIONS.INVITE_MEMBERS, PERMISSIONS.REMOVE_MEMBERS, PERMISSIONS.CHANGE_ROLES, PERMISSIONS.VIEW_ORGANIZATION ],
    [ ROLES.ADMIN ] : [ PERMISSIONS.INVITE_MEMBERS, PERMISSIONS.REMOVE_MEMBERS, PERMISSIONS.VIEW_ORGANIZATION ],
    [ ROLES.MEMBER ] : [ PERMISSIONS.VIEW_ORGANIZATION ]
};

export { ROLES, PERMISSIONS, ROLE_PERMISSION };